apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment #deployment name
  labels:
    app: todo
spec:
  replicas: 3  # define number of pods 
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-ver1  # docker image name
        image: todo:prod
        imagePullPolicy: IfNotPresent # forces to check for a image locally first 
        ports:
        - containerPort: 5000
