apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP  #port mapping
      port: 80
      targetPort: 5000
  type: LoadBalancer # as we need the external access
